{{- if .Values.dbimage.enableTestDb }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fossology.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
{{ include "fossology.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-scheduler
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.dbimage.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                 {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_user
            - name: POSTGRES_INITDB_ARGS
              value: '-E SQL_ASCII'
          ports:
            - name: postgrsql
              containerPort: {{ .Values.fossology.db_port}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
