apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fossology.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-scheduler
    {{- include "fossology.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name:  {{ include "fossology.fullname" . }}-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  {{ include "fossology.fullname" . }}-scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FOSSOLOGY_DB_HOST
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_host
            - name: FOSSOLOGY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_password
            - name: FOSSOLOGY_DB_NAME
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_name
            - name: FOSSOLOGY_DB_USER
              valueFrom:
                secretKeyRef:
                {{- if .Values.fossology.externalSecret }}
                 name: {{ .Values.fossology.externalSecret }}
                {{- else }}
                 name: {{ template "fossology.fullname" . }}
                {{- end }}
                 key: db_user
          ports:
            - name: scheduler
              containerPort: 80
              protocol: TCP
          command:
             - "/fossology/docker-entrypoint.sh"
             - "scheduler"
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: cache-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cache-volume
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "fossology.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{ end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
